### PR TITLE
Touch user for cache invalidation

### PR DESCRIPTION
**Pull request by ikataitsev**
This PR adds touch calls for available user record so the cache validation can happen if any.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @ikataitsev, thanks for the PR. I don’t think this change is desired in most cases, so don’t think it makes sense to merge.

**Comment by ikataitsev** [comment]
Hey @ankane, thanks for a response. Do you think broadcasting unsubscribe and subscribe events via `ActiveSupport::Notifications` would be an acceptable approach for this case?

**Comment by ankane** [comment]
@ikataitsev yeah, I think that would work. Feel free to submit a PR

**Comment by ankane** [comment]
Update the PR *

**Comment by ankane** [comment]
Cleaning up PRs

**Pull request closed without merging**
